name: CI

on:
  - pull_request

jobs:
  lint:
    name: Source code formatting & spellcheck
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check formatting with Prettier
        run: pnpm format:check

      - name: Spellcheck
        run: pnpm spellcheck

  typecheck:
    name: Typecheck & linting
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint with ESLint
        run: pnpm lint

      - name: Check Typescript
        run: |
          pnpm typecheck
